export enum ErrorCodes {
  INVALID_INPUT = 'INVALID_INPUT',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TEMPLATE_PROCESSING_ERROR = 'TEMPLATE_PROCESSING_ERROR',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
}
